// 推广数据字段名常量 — 通过 findField 做模糊匹配，无需与导出文件字段名完全一致
export const PROMO_FIELDS = {
  cost:        ['总花费(元)', '花费(元)', '成交花费(元)', '推广花费'],
  orders:      ['成交笔数', '推广订单数', '订单数'],
  gmv:         ['交易额(元)', '成交金额(元)', '推广GMV', '总成交金额'],
  impressions: ['曝光量', '展现量'],
  clicks:      ['点击量'],
  ctr:         ['点击率'],
  cvr:         ['转化率'],
  date:        ['日期', 'date'],
  productId:   ['商品ID', '商品id', '商品编号'],
  productName: ['商品名称', '商品'],
  keyword:     ['推广名称', '关键词'],
  scene:       ['场景', '投放场景', '推广场景'],
  cpc:         ['平均点击花费(元)', '单次点击花费'],
  inquiry:     ['询单量', '询单'],
  inquiryCost: ['询单花费(元)', '询单花费'],
  favorite:    ['收藏量', '收藏'],
  favoriteCost:['收藏花费(元)', '收藏花费'],
  follow:      ['关注量', '关注'],
  followCost:  ['关注花费(元)', '关注花费'],
  comment:     ['直播评论量', '评论量', '评论'],
  deepView:    ['深度观看'],
  storeFollow: ['店铺关注量', '店铺关注'],
} as const;
